<a href="https://colab.research.google.com/github/Computer-CGuy/RoboKnightSubmission/blob/master/Motion_Planning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
path = np.zeros((4,4))

In [ ]:
int(path.sum())==0

In [ ]:
path = np.zeros((4,4))
path[0,0]=0
path[0,1]=2
path[0,2]=2
path[0,3]=1

path[1,0]=2
path[1,1]=0
path[1,2]=0
path[1,3]=1

path[2,0]=2
path[2,1]=0
path[2,2]=0
path[2,3]=1

path[3,0]=1
path[3,1]=1
path[3,2]=1
path[3,3]=0

print(path)


[[0. 2. 2. 1.]
 [2. 0. 0. 1.]
 [2. 0. 0. 1.]
 [1. 1. 1. 0.]]


In [ ]:
A,B,C,D = 0,1,2,3

In [ ]:
mina = 9999
def solve(x,l):
    global mina
    # if(path.sum()<mina):
        # print(path)
    global path
    if(int(path.sum())==0):
        print(l)
        min = path.sum()
        # return
    for y in range(path.shape[1]):
        if(path[x,y]!=0):
            path[x,y]-=1
            path[y,x]-=1
            solve(y,l+[y])
            path[x,y]+=1
            path[y,x]+=1

In [ ]:
for x in range(4):
    solve(x,[])

In [ ]:
def set(x,y):
    global path
    path[x,y]+=1
    path[y,x]+=1
    

In [ ]:
path = np.zeros((8,8))
set(0,1)
set(0,4)
set(0,3)
set(3,7)
set(2,3)    
set(2,6)
set(1,2)
set(1,5)
set(5,6)
set(4,5)
set(4,7)
set(6,7)

In [ ]:
for x in range(7):
    solve(x,[])

In [ ]:
path = np.zeros((6,6))
set(0,1)
set(0,2)
set(1,2)
set(1,5)
set(1,4)
set(2,3)
set(2,5)
set(3,5)
set(3,4)
set(4,5)

In [ ]:
for x in range(6):
    solve(x,[])

[2, 0, 1, 2, 5, 1, 4, 3, 5, 4]
[2, 0, 1, 2, 5, 1, 4, 5, 3, 4]
[2, 0, 1, 2, 5, 3, 4, 1, 5, 4]
[2, 0, 1, 2, 5, 3, 4, 5, 1, 4]
[2, 0, 1, 2, 5, 4, 1, 5, 3, 4]
[2, 0, 1, 2, 5, 4, 3, 5, 1, 4]
[2, 0, 1, 4, 3, 5, 1, 2, 5, 4]
[2, 0, 1, 4, 3, 5, 2, 1, 5, 4]
[2, 0, 1, 4, 5, 1, 2, 5, 3, 4]
[2, 0, 1, 4, 5, 2, 1, 5, 3, 4]
[2, 0, 1, 5, 2, 1, 4, 3, 5, 4]
[2, 0, 1, 5, 2, 1, 4, 5, 3, 4]
[2, 0, 1, 5, 3, 4, 1, 2, 5, 4]
[2, 0, 1, 5, 3, 4, 5, 2, 1, 4]
[2, 0, 1, 5, 4, 1, 2, 5, 3, 4]
[2, 0, 1, 5, 4, 3, 5, 2, 1, 4]
[2, 1, 0, 2, 5, 1, 4, 3, 5, 4]
[2, 1, 0, 2, 5, 1, 4, 5, 3, 4]
[2, 1, 0, 2, 5, 3, 4, 1, 5, 4]
[2, 1, 0, 2, 5, 3, 4, 5, 1, 4]
[2, 1, 0, 2, 5, 4, 1, 5, 3, 4]
[2, 1, 0, 2, 5, 4, 3, 5, 1, 4]
[2, 1, 4, 3, 5, 1, 0, 2, 5, 4]
[2, 1, 4, 3, 5, 2, 0, 1, 5, 4]
[2, 1, 4, 5, 1, 0, 2, 5, 3, 4]
[2, 1, 4, 5, 2, 0, 1, 5, 3, 4]
[2, 1, 5, 2, 0, 1, 4, 3, 5, 4]
[2, 1, 5, 2, 0, 1, 4, 5, 3, 4]
[2, 1, 5, 3, 4, 1, 0, 2, 5, 4]
[2, 1, 5, 3, 4, 5, 2, 0, 1, 4]
[2, 1, 5, 4, 1, 0, 2, 5, 3, 4]
[2, 1, 5, 4, 3, 5, 2, 0, 1, 4]
[2, 5, 1

In [ ]:
path = np.zeros((7,7))
set(0,1)
set(0,2)

set(1,3)

set(2,3)
set(2,3)
set(2,3)
set(2,4)

set(3,6)

set(4,6)
set(4,5)

set(5,6)

In [ ]:
for x in range(7):
    solve(x,[])

In [ ]:
path = np.zeros((3,3))
set(0,1)
set(0,1)
set(0,1)

set(0,2)
set(0,2)
set(0,2)

set(1,2)
set(1,2)


In [ ]:
for x in range(3):
    solve(x,[])

[0, 1, 0, 2, 0, 2, 1, 2]
[0, 1, 0, 2, 1, 2, 0, 2]
[0, 1, 2, 0, 1, 2, 0, 2]
[0, 1, 2, 0, 2, 0, 1, 2]
[0, 1, 2, 0, 2, 1, 0, 2]
[0, 1, 2, 1, 0, 2, 0, 2]
[0, 2, 0, 1, 0, 2, 1, 2]
[0, 2, 0, 1, 2, 0, 1, 2]
[0, 2, 0, 1, 2, 1, 0, 2]
[0, 2, 0, 2, 1, 0, 1, 2]
[0, 2, 1, 0, 1, 2, 0, 2]
[0, 2, 1, 0, 2, 0, 1, 2]
[0, 2, 1, 0, 2, 1, 0, 2]
[0, 2, 1, 2, 0, 1, 0, 2]
[2, 0, 1, 0, 1, 2, 0, 2]
[2, 0, 1, 0, 2, 0, 1, 2]
[2, 0, 1, 0, 2, 1, 0, 2]
[2, 0, 1, 2, 0, 1, 0, 2]
[2, 0, 2, 0, 1, 0, 1, 2]
[2, 0, 2, 1, 0, 1, 0, 2]
[2, 1, 0, 1, 0, 2, 0, 2]
[2, 1, 0, 2, 0, 1, 0, 2]
[0, 1, 0, 1, 2, 0, 2, 1]
[0, 1, 0, 2, 0, 1, 2, 1]
[0, 1, 0, 2, 1, 0, 2, 1]
[0, 1, 0, 2, 1, 2, 0, 1]
[0, 1, 2, 0, 1, 0, 2, 1]
[0, 1, 2, 0, 1, 2, 0, 1]
[0, 1, 2, 0, 2, 1, 0, 1]
[0, 1, 2, 1, 0, 2, 0, 1]
[0, 2, 0, 1, 0, 1, 2, 1]
[0, 2, 0, 1, 2, 1, 0, 1]
[0, 2, 1, 0, 1, 0, 2, 1]
[0, 2, 1, 0, 1, 2, 0, 1]
[0, 2, 1, 0, 2, 1, 0, 1]
[0, 2, 1, 2, 0, 1, 0, 1]
[1, 0, 1, 0, 2, 0, 2, 1]
[1, 0, 1, 2, 0, 2, 0, 1]
[1, 0, 2, 0, 1, 0, 2, 1]
[1, 0, 2, 0, 1, 2, 0, 1]


In [ ]:
path = np.zeros((10,10))
set(0,1)
set(0,9)

set(1,2)
set(1,3)
set(1,9)

set(8,9)

set(3,4)
set(4,5)
set(4,6)

set(6,8)
set(6,7)

set(7,8)

set(5,6)

set(2,3)

In [ ]:
for x in range(10):
    solve(x,[])

In [ ]:
path = np.zeros((9,9))
set(0,1)
set(0,8)

set(1,2)

set(2,3)
set(2,5)
set(2,8)

set(3,4)

set(4,5)

set(5,6)
set(5,8)

set(6,7)

set(7,8)


In [ ]:
for x in range(9):
    solve(x,[])

[1, 2, 3, 4, 5, 2, 8, 5, 6, 7, 8, 0]
[1, 2, 3, 4, 5, 2, 8, 7, 6, 5, 8, 0]
[1, 2, 3, 4, 5, 6, 7, 8, 2, 5, 8, 0]
[1, 2, 3, 4, 5, 6, 7, 8, 5, 2, 8, 0]
[1, 2, 3, 4, 5, 8, 2, 5, 6, 7, 8, 0]
[1, 2, 3, 4, 5, 8, 7, 6, 5, 2, 8, 0]
[1, 2, 5, 4, 3, 2, 8, 5, 6, 7, 8, 0]
[1, 2, 5, 4, 3, 2, 8, 7, 6, 5, 8, 0]
[1, 2, 5, 6, 7, 8, 2, 3, 4, 5, 8, 0]
[1, 2, 5, 6, 7, 8, 5, 4, 3, 2, 8, 0]
[1, 2, 5, 8, 2, 3, 4, 5, 6, 7, 8, 0]
[1, 2, 5, 8, 7, 6, 5, 4, 3, 2, 8, 0]
[1, 2, 8, 5, 2, 3, 4, 5, 6, 7, 8, 0]
[1, 2, 8, 5, 4, 3, 2, 5, 6, 7, 8, 0]
[1, 2, 8, 7, 6, 5, 2, 3, 4, 5, 8, 0]
[1, 2, 8, 7, 6, 5, 4, 3, 2, 5, 8, 0]
[8, 2, 3, 4, 5, 6, 7, 8, 5, 2, 1, 0]
[8, 2, 3, 4, 5, 8, 7, 6, 5, 2, 1, 0]
[8, 2, 5, 6, 7, 8, 5, 4, 3, 2, 1, 0]
[8, 2, 5, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[8, 5, 2, 3, 4, 5, 6, 7, 8, 2, 1, 0]
[8, 5, 2, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[8, 5, 4, 3, 2, 5, 6, 7, 8, 2, 1, 0]
[8, 5, 4, 3, 2, 8, 7, 6, 5, 2, 1, 0]
[8, 5, 6, 7, 8, 2, 3, 4, 5, 2, 1, 0]
[8, 5, 6, 7, 8, 2, 5, 4, 3, 2, 1, 0]
[8, 7, 6, 5, 2, 3, 4, 5, 8, 2, 1, 0]
[